ls:
  packages/{src,__tests__}:
    .js: camelCase
    .ts: camelCase
    .d.ts: camelCase
    .spec.ts: camelCase | PascalCase

  # dev/*/{src}:
  #   .js: camelCase
  #   .ts: camelCase
  #   .jsx: camelCase
  #   .tsx: camelCase
  #   .d.ts: camelCase

  website/{src,docs}:
    .js: camelCase
    .ts: camelCase
    .jsx: camelCase
    .tsx: camelCase
    .d.ts: camelCase

  scripts:
    .js: camelCase

