name: 'codecov'
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  update-coverage:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.17.0]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache .pnpm-store
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
    - name: Install pnpm
      run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6
    - name: install dependency
      run: pnpm install --filter=\!garfish-docs --filter=\!@garfish-dev/\*
    - name: Run unit tests
      run: pnpm test
    - name: codecov
      run: npx codecov -f coverage/*.json
